import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Sidebar from '@/components/Sidebar'
import Header from '@/components/Header'
import Logo from '@/components/Logo'
import prisma from '@/lib/db'
import { ThemeProvider } from 'next-themes'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  const boards = await prisma.board.findMany()

  return (
    <html lang='en' suppressHydrationWarning>
      <body className={inter.className}>
        <ThemeProvider
          attribute='class'
          defaultTheme='system'
          enableSystem
          disableTransitionOnChange
        >
          <div className='flex flex-col h-screen'>
            <div className='flex bg-card'>
              <Logo />
              <Header boards={boards} />
            </div>
            <div className='flex h-full overflow-auto'>
              <Sidebar boards={boards} />
              {children}
            </div>
          </div>
        </ThemeProvider>
      </body>
    </html>
  )
}
